image:
  tag: "0000000000000000000000000000000000000000" # {"$imagepolicy": "production:openfilter-pipelines-controller:tag"}
claimerImage:
  tag: "0000000000000000000000000000000000000000" # {"$imagepolicy": "production:openfilter-pipelines-controller:tag"}

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

telemetry:
  exporterType: otlp
  exporterOtlpEndpoint: otel-collector.monitoring.svc.cluster.local:4317
