apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-exec-role
  namespace: default
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/component: pipeline-executor
rules:
  # Allows claimer init container to patch pod annotations with queue metadata
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
