# This rule is not used by the project openfilter-pipelines-runner itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to filter.plainsight.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-runner
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-viewer-role
rules:
- apiGroups:
  - filter.plainsight.ai
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - filter.plainsight.ai
  resources:
  - pipelines/status
  verbs:
  - get
