apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: default
