apiVersion: pipelines.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-runner
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
