apiVersion: pipelines.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-runner
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-minio-sample
spec:
  input:
    bucket: pipeline-data
    prefix: datasets/
    endpoint: http://minio.default.svc.cluster.local:9000
    usePathStyle: true
    credentialsSecret:
      name: minio-credentials
