apiVersion: filter.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
spec:
  source:
    bucket:
      name: cow-demo-development
      prefix: videos
      endpoint: storage.googleapis.com
      credentialsSecret:
        name: gcs-credentials
  videoInputPath: /ws/input.mp4

  # Global configuration that will be injected as FILTER_* env vars into all filter containers
  config:
    - name: sources
      value: tcp://localhost:5550
    - name: outputs
      value: tcp://*:5551

  filters:
    - name: video-in
      image: plainsightai/openfilter-videoin:v0.1.10
      # These filters will inherit FILTER_SOURCES=tcp://localhost:5550 and FILTER_OUTPUTS=tcp://*:5551
      # from the config above. Individual filters can override these by specifying their own env vars.
    - name: face-blur
      image: plainsightai/openfilter-faceblur:v1.1.4
      # This filter also inherits the config env vars
