apiVersion: filter.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
spec:
  source:
    bucket:
      name: cow-demo-development
      prefix: videos
      endpoint: storage.googleapis.com
      credentialsSecret:
        name: gcs-credentials

  execution:
    parallelism: 10
    maxAttempts: 3
    pendingTimeout: 15m # Kubernetes duration format (e.g., "15m", "1h", "30s")

  filters:
    - name: list-file
      image: alpine:latest
      command: ["ls"]
      args: ["-la", "/ws/input"]
