apiVersion: filter.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-gcs-sample
spec:
  input:
    bucket: my-gcs-bucket
    prefix: pipeline-inputs/
    endpoint: https://storage.googleapis.com
    credentialsSecret:
      name: gcs-s3-credentials
