apiVersion: filter.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-sample
spec:
  source:
    bucket:
      name: cow-demo-development
      prefix: videos
      endpoint: storage.googleapis.com
      credentialsSecret:
        name: gcs-credentials
  videoInputPath: /ws/input.mp4

  filters:
    - name: video-in
      image: plainsightai/openfilter-video-in:v0.1.10
      config:
        - name: sources
          value: file:///ws/input.mp4
        - name: outputs
          value: tcp://*:5550
    - name: face-blur
      image: plainsightai/openfilter-faceblur:v1.1.4
      config:
        - name: sources
          value: tcp://localhost:5550
        - name: outputs
          value: tcp://*:5552
