apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: system
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: valkey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: system
spec:
  selector:
    matchLabels:
      app: valkey
  replicas: 1
  template:
    metadata:
      labels:
        app: valkey
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: valkey
        image: valkey/valkey:8.0-alpine
        ports:
        - containerPort: 6379
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
