apiVersion: filter.plainsight.ai/v1alpha1
kind: PipelineRun
metadata:
  generateName: pipelinerun-batch-
spec:
  pipelineRef:
    name: pipeline-batch
  source:
    bucket:
      name: cow-demo-development
      prefix: videos
      endpoint: storage.googleapis.com
      credentialsSecret:
        name: gcs-credentials
  execution:
    parallelism: 1
    maxAttempts: 3
    pendingTimeout: "5m"
