apiVersion: filter.plainsight.ai/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-batch
spec:
  mode: batch
  source:
    bucket:
      name: cow-demo-development
      prefix: videos
      endpoint: storage.googleapis.com
      credentialsSecret:
        name: gcs-credentials
  videoInputPath: /ws/input.mp4

  filters:
    - name: video-in
      image: plainsightai/openfilter-video-in:v0.1.10
      resources:
        requests:
          cpu: "1"
        limits:
          cpu: "1"
      config:
        - name: sources
          value: file:///ws/input.mp4
        - name: outputs
          value: tcp://*:5550
      env:
        - name: LOG_LEVEL
          value: debug
    - name: image-out
      image: plainsightai/openfilter-image-out:v0.1.14
      config:
        - name: sources
          value: tcp://localhost:5550
        - name: outputs
          value: "file:///ws/images_%Y%m%d_%H%M%S_%d.png"
        - name: bgr
          value: "true"
        - name: format
          value: "png"
        - name: quality
          value: "90"
        - name: compression
          value: "6"
