apiVersion: filter.plainsight.ai/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-rtsp
spec:
  pipelineRef:
    name: pipeline-rtsp
  source:
    rtsp:
      host: rtsp-video-stream
      port: 8554
      path: /stream
      # credentialsSecret:
      #   name: axis-rtsp-credentials
